### ISSUE TITLE
hello，关于ip签名档的问题

### ISSUE THREAD

**Issue by owllen** [xhboke/xhboke#1]
由于你的ip项目已经Archived，无法提交issue，所以找到这里希望能联系上你，希望能请教
问题如下：我按照你的开源代码clone过去，在本地服务器（win10）上可以运行，开始时报错
发现是载入字体文件时的路径问题，修改后可正常运行
第30行修改后为" $font = 'E:\test\IP-master\msyh.ttf'; ”
上传至线上服务器中（centos+apache+mysql+php），确无法正常显示
尝试了修改路径
"$font = 'msyh.ttf'; ”
"$font = '/ipdm/msyh.ttf'; ”
"$font = '../msyh.ttf'; ”
均无法正常运行，最终显示的图片只有一个小方快
应为对php不是很熟悉，一直折腾到现在，请问下是否是我这块的路径设置原因导致的呢？
望指教

**Comment by owllen** [comment]
可能描述不太清楚，这是我上线的url位置 https://www.log-ing.com/ipqmd/

**Comment by xhboke** [comment]
显示小方格，应该是某句或多句代码运行出错，可根据适当删除部分代码来排除问题。
关于字体加载问题，php版本的不同有些许差异，可尝试用“./”表示当前目录，例如‘./msyh.ttf’尝试下。

--------------原始邮件--------------
发件人："owllen "<notifications@github.com&gt;;
发送时间：2021年3月5日(星期五) 凌晨5:20
收件人："xhboke/xhboke" <xhboke@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[xhboke/xhboke] hello，关于ip签名档的问题 (#1)
-----------------------------------

 

 
由于你的ip项目已经Archived，无法提交issue，所以找到这里希望能联系上你，希望能请教
 问题如下：我按照你的开源代码clone过去，在本地服务器（win10）上可以运行，开始时报错
 发现是载入字体文件时的路径问题，修改后可正常运行
 第30行修改后为" $font = 'E:\test\IP-master\msyh.ttf'; ”
 上传至线上服务器中（centos+apache+mysql+php），确无法正常显示
 尝试了修改路径
 "$font = 'msyh.ttf'; ”
 "$font = '/ipdm/msyh.ttf'; ”
 "$font = '../msyh.ttf'; ”
 均无法正常运行，最终显示的图片只有一个小方快
 应为对php不是很熟悉，一直折腾到现在，请问下是否是我这块的路径设置原因导致的呢？
 望指教

**Comment by owllen** [comment]
感谢，问题解决了，不是路径的原因。
查了一整天，各种测试，最终发现是我的**线上php版本gd 2.1.0 拓展库不支持jpeg**造成的（之前升级php编译时未加参数“--with-jpeg-dir”），**导致”$im = imagecreatefromjpeg("xhxh.jpg");“一直无法正常加载图片**，而线上运行一直无报错信息应该与index.php文件中“header("Content-type: image/JPEG");”有关，注释这句后运行报错，才发现的问题所在，最后直接先把原底图xhxh.jpg转成xhxh.gif放进去才正常运行（加jpeg支持太繁琐要重新编译php，太累了...)
最后感谢你的热心解答!
